// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkteeqjapxesngszdouo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdGVlcWphcHhlc25nc3pkb3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDk5NjgsImV4cCI6MjA2Nzg4NTk2OH0.iapadpt5bGxEIG3mF09W0zSx8TZWRwo4qM5Pp8ooQgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});